// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS9C03SIoJWO0jyTrMkhQOp8Rm6qDNgqI',
    appId: '1:764733105402:web:4db3d81abc8b7244855543',
    messagingSenderId: '764733105402',
    projectId: 'iconicfeed-9cb86',
    authDomain: 'iconicfeed-9cb86.firebaseapp.com',
    storageBucket: 'iconicfeed-9cb86.appspot.com',
    measurementId: 'G-YLK6VJ2WPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGF2Hj27Q2IDGj_Glo7gZMbPX8Y8eDJJo',
    appId: '1:764733105402:android:5a247382a9bd1410855543',
    messagingSenderId: '764733105402',
    projectId: 'iconicfeed-9cb86',
    storageBucket: 'iconicfeed-9cb86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9V41zXE_z_C9K7m9yNqhIjNWK_YxR1c',
    appId: '1:764733105402:ios:8edbd4d2d009ea4d855543',
    messagingSenderId: '764733105402',
    projectId: 'iconicfeed-9cb86',
    storageBucket: 'iconicfeed-9cb86.appspot.com',
    iosBundleId: 'com.example.real.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE9V41zXE_z_C9K7m9yNqhIjNWK_YxR1c',
    appId: '1:764733105402:ios:360cf08491d9a216855543',
    messagingSenderId: '764733105402',
    projectId: 'iconicfeed-9cb86',
    storageBucket: 'iconicfeed-9cb86.appspot.com',
    iosBundleId: 'com.example.real.realEstate.RunnerTests',
  );
}
